# Generated by Django 3.1.4 on 2020-12-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('frames', models.IntegerField()),
                ('frame_rate', models.CharField(max_length=155)),
                ('url', models.CharField(max_length=155)),
                ('first_frame', models.CharField(max_length=155)),
                ('last_frame', models.CharField(max_length=155)),
            ],
        ),
    ]
