# Generated by Django 3.1.4 on 2020-12-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='first_frame',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='video',
            name='frame_rate',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='video',
            name='frames',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='last_frame',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='video',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
